Repository MAKAIABootcamp/gestaCourse-project-frontend-6, pull requests merged in 2024-01, with the labels that each got.

#33 Routas publicas y privadas
  package-lock.json
  package.json
  src/components/Login/Login.jsx
  src/components/NavBar/NavBar.jsx
  src/routes/PrivatedRoutes.jsx
  src/routes/PublicRoutes.jsx
  src/routes/Router.jsx
  src/store/users/userActions.js
  src/store/users/userSlice.js
Labels: Autenticación

#34 31 desarrollar funcionalidades estudiante
  src/components/Layout/Layout.jsx
  src/components/Login/Login.jsx
  src/components/NavBar/NavBar.jsx
  src/firebase/firebaseConfig.js
  src/pages/DeatailsCourse/DetailsCourse.jsx
  src/pages/EditProfile/EditProfile.jsx
  src/pages/MyCourses/MyCourses.jsx
  src/routes/Router.jsx
  src/services/useServices.js
  src/store/courses/coursesActions.js
  src/store/courses/coursesSlice.js
  src/store/enrollment/enrollmentActions.js
  src/store/enrollment/enrollmentSlice.js
  src/store/store.js
  src/store/users/userActions.js
  src/store/users/userSlice.js
Labels: Autenticación

#40 31 desarrollar funcionalidades estudiante
  src/components/Login/Login.jsx
  src/components/NavBar/NavBar.jsx
  src/pages/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/pages/EditProfile/EditProfile.jsx
  src/pages/OfertasInscripciones/OfertasInscripciones.jsx
  src/pages/OfertasInscripciones/StyleOfertasInscripciones.jsx
  src/pages/Page404/Page404.css
  src/pages/Page404/Page404.jsx
  src/routes/Router.jsx
  src/services/useServices.js
  src/store/users/userActions.js
  src/store/users/userSlice.js
Labels: Autenticación

#45 31 desarrollar funcionalidades estudiante
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/StyleNavBar.jsx
  src/components/courseManagementTable/courseManagementTable.jsx
  src/components/courseManagementTable/courseManagementTableStyle.jsx
  src/pages/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/pages/EditProfile/EditProfile.jsx
  src/pages/OfertasInscripciones/StyleOfertasInscripciones.jsx
Labels: Maquetación

#57 Se añade filtro de estudiantes
  src/components/NavBar/NavBar.jsx
  src/pages/StudentsForCourse/StudentsForCourse.jsx
Labels: Funcionalidad
